<?xml version="1.0" ?>
<testsuite errors="4" failures="0" name="Tests.RCR_VR_HA_Service_ConfigTool_Organization_Map_PUT.TestOrganizationMapsDev-20180712130640" tests="4" time="0.000">
	<testcase classname="Tests.RCR_VR_HA_Service_ConfigTool_Organization_Map_PUT.TestOrganizationMapsDev" name="test_Step1_putRequest_newID_validParams" time="0.000">
		<error message="Auth() missing 1 required positional argument: 'self'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "C:\Users\SC057441\Desktop\Any\pythonscripts\tokka\yamlgenerator\Requests\Final_Suite\Tests\RCR_VR_HA_Service_ConfigTool_Organization_Map_PUT.py", line 18, in setUp
    self.oAuth = oAuthGenerator.Auth()
TypeError: Auth() missing 1 required positional argument: 'self'
]]>		</error>
	</testcase>
	<testcase classname="Tests.RCR_VR_HA_Service_ConfigTool_Organization_Map_PUT.TestOrganizationMapsDev" name="test_Step2_putRequest_newID_invalidParams_error" time="0.000">
		<error message="Auth() missing 1 required positional argument: 'self'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "C:\Users\SC057441\Desktop\Any\pythonscripts\tokka\yamlgenerator\Requests\Final_Suite\Tests\RCR_VR_HA_Service_ConfigTool_Organization_Map_PUT.py", line 18, in setUp
    self.oAuth = oAuthGenerator.Auth()
TypeError: Auth() missing 1 required positional argument: 'self'
]]>		</error>
	</testcase>
	<testcase classname="Tests.RCR_VR_HA_Service_ConfigTool_Organization_Map_PUT.TestOrganizationMapsDev" name="test_Step3_putRequest_IDExists_validParams" time="0.000">
		<error message="Auth() missing 1 required positional argument: 'self'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "C:\Users\SC057441\Desktop\Any\pythonscripts\tokka\yamlgenerator\Requests\Final_Suite\Tests\RCR_VR_HA_Service_ConfigTool_Organization_Map_PUT.py", line 18, in setUp
    self.oAuth = oAuthGenerator.Auth()
TypeError: Auth() missing 1 required positional argument: 'self'
]]>		</error>
	</testcase>
	<testcase classname="Tests.RCR_VR_HA_Service_ConfigTool_Organization_Map_PUT.TestOrganizationMapsDev" name="test_Step4_putRequest_IDExists_invalidParams_error" time="0.000">
		<error message="Auth() missing 1 required positional argument: 'self'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "C:\Users\SC057441\Desktop\Any\pythonscripts\tokka\yamlgenerator\Requests\Final_Suite\Tests\RCR_VR_HA_Service_ConfigTool_Organization_Map_PUT.py", line 18, in setUp
    self.oAuth = oAuthGenerator.Auth()
TypeError: Auth() missing 1 required positional argument: 'self'
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
