<?xml version="1.0" ?>
<testsuite errors="2" failures="0" name="Tests.RCR_VR_HA_Service_ConfigTool_Age_Categories_PUT.TestAgeCategoriesPut-20180712130640" tests="2" time="0.000">
	<testcase classname="Tests.RCR_VR_HA_Service_ConfigTool_Age_Categories_PUT.TestAgeCategoriesPut" name="test_Step1_putRequest" time="0.000">
		<error message="Auth() missing 1 required positional argument: 'self'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "C:\Users\SC057441\Desktop\Any\pythonscripts\tokka\yamlgenerator\Requests\Final_Suite\Tests\RCR_VR_HA_Service_ConfigTool_Age_Categories_PUT.py", line 18, in setUp
    self.oAuth = oAuthGenerator.Auth()
TypeError: Auth() missing 1 required positional argument: 'self'
]]>		</error>
	</testcase>
	<testcase classname="Tests.RCR_VR_HA_Service_ConfigTool_Age_Categories_PUT.TestAgeCategoriesPut" name="test_Step2_putRequest_error" time="0.000">
		<error message="Auth() missing 1 required positional argument: 'self'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "C:\Users\SC057441\Desktop\Any\pythonscripts\tokka\yamlgenerator\Requests\Final_Suite\Tests\RCR_VR_HA_Service_ConfigTool_Age_Categories_PUT.py", line 18, in setUp
    self.oAuth = oAuthGenerator.Auth()
TypeError: Auth() missing 1 required positional argument: 'self'
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
