<?xml version="1.0" ?>
<testsuite errors="1" failures="0" name="Tests.RCR_VR_HA_Service_ConfigTool_Config_Items_PUT.TestSuiteConfigItemsPut-20180712164354" tests="4" time="20.946">
	<testcase classname="Tests.RCR_VR_HA_Service_ConfigTool_Config_Items_PUT.TestSuiteConfigItemsPut" name="test_Step001_postRequest_new_id" time="5.949"/>
	<testcase classname="Tests.RCR_VR_HA_Service_ConfigTool_Config_Items_PUT.TestSuiteConfigItemsPut" name="test_Step002_putRequest_invalid_config_id" time="5.029"/>
	<testcase classname="Tests.RCR_VR_HA_Service_ConfigTool_Config_Items_PUT.TestSuiteConfigItemsPut" name="test_Step003_putRequest_empty_key_value" time="5.439"/>
	<testcase classname="Tests.RCR_VR_HA_Service_ConfigTool_Config_Items_PUT.TestSuiteConfigItemsPut" name="test_Step004_putRequest_empty_clientid" time="4.530">
		<error message="list index out of range" type="IndexError">
<![CDATA[Traceback (most recent call last):
  File "C:\Users\SC057441\Desktop\Any\pythonscripts\tokka\yamlgenerator\Requests\Final_Suite\Tests\RCR_VR_HA_Service_ConfigTool_Config_Items_PUT.py", line 50, in test_Step004_putRequest_empty_clientid
    completeURL = str(self.GET_URL) + "/" + self.id_table[0]
IndexError: list index out of range
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[java -jar Tests\auth-header-1.3.jar -k 99bb308b-0a2b-4547-a967-b6287914469d -s cHowMqwBMh2N4ShhBDrbcRZNLzo76VrA -p https://api.devcernercare.com/oauth/access > oAuthKey.txt
java -jar Tests\auth-header-1.3.jar -k 99bb308b-0a2b-4547-a967-b6287914469d -s cHowMqwBMh2N4ShhBDrbcRZNLzo76VrA -p https://api.devcernercare.com/oauth/access > oAuthKey.txt
java -jar Tests\auth-header-1.3.jar -k 99bb308b-0a2b-4547-a967-b6287914469d -s cHowMqwBMh2N4ShhBDrbcRZNLzo76VrA -p https://api.devcernercare.com/oauth/access > oAuthKey.txt
java -jar Tests\auth-header-1.3.jar -k 99bb308b-0a2b-4547-a967-b6287914469d -s cHowMqwBMh2N4ShhBDrbcRZNLzo76VrA -p https://api.devcernercare.com/oauth/access > oAuthKey.txt
[]
]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
